global:
  resolve_timeout: 5m

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'solomonjass4@gmail.com'
        from: 'capstonealertmanager@gmail.com'
        smarthost: 'smtp@gmail.com:587'
        auth_username: 'capstonealertmanager@gmail.com'
        auth_password: 'root'
