# prometheus.yml
global:
  scrape_interval: 15s  # How often to scrape metrics

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['group-bsse24-25-2.onrender.com:4001']  # Replace with your backend's address and port

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - "alerts.yml"