name: Super-Linter

on:
  push:
    branches:
      - LintCodeBase # Run only on your branch
  pull_request:
    branches:
      - LintCodeBase # Run only on your branch

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
