name: Super-Linter

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLED_LINTERS: eslint,json  # Lint only specific languages
          LINTER_RULES_PATH: .github/linter.yml  # Optional custom rules configuration
